### ISSUE TITLE
Not working for Visual Studio 2017

### ISSUE THREAD

**Issue by morphx666** [DavidMoore/VisualBasic6X#2]
When trying to install this AddIn and the only installed version of Visual Studio is 2017, it fails with the following error message:

3/9/2017 2:17:46 AM - Microsoft VSIX Installer
3/9/2017 2:17:46 AM - -------------------------------------------
3/9/2017 2:17:46 AM - vsixinstaller.exe version:
3/9/2017 2:17:46 AM - 15.0.26228.0 built by: D15REL
3/9/2017 2:17:46 AM - -------------------------------------------
3/9/2017 2:17:46 AM - Command line parameters:
3/9/2017 2:17:46 AM - d:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,D:\Users\Xavier\Downloads\VisualBasic6X.vsix
3/9/2017 2:17:46 AM - -------------------------------------------
3/9/2017 2:17:46 AM - Microsoft VSIX Installer
3/9/2017 2:17:46 AM - -------------------------------------------
3/9/2017 2:17:47 AM - Initializing Install...
3/9/2017 2:17:47 AM - Extension Details...
3/9/2017 2:17:47 AM - 	Identifier         : 5AAC6560-7DB2-420B-B6CF-3E68AF499341
3/9/2017 2:17:47 AM - 	Name               : Visual Basic 6X
3/9/2017 2:17:47 AM - 	Author             : David Moore
3/9/2017 2:17:47 AM - 	Version            : 1.0.0.1
3/9/2017 2:17:47 AM - 	Description        : Visual Basic 6 integration into Visual Studio
3/9/2017 2:17:47 AM - 	Locale             : en-US
3/9/2017 2:17:47 AM - 	MoreInfoURL        : 
3/9/2017 2:17:47 AM - 	InstalledByMSI     : False
3/9/2017 2:17:47 AM - 	SupportedFrameworkVersionRange : [4.0,4.5]
3/9/2017 2:17:47 AM - 
3/9/2017 2:17:47 AM - 	SignatureState     : Unsigned
3/9/2017 2:17:47 AM - 	Supported Products : 
3/9/2017 2:17:47 AM - 		Microsoft.VisualStudio.Pro
3/9/2017 2:17:47 AM - 			Version : [12.0]
3/9/2017 2:17:47 AM - 		Microsoft.VisualStudio.Pro
3/9/2017 2:17:47 AM - 			Version : [11.0]
3/9/2017 2:17:47 AM - 		Microsoft.VisualStudio.Pro
3/9/2017 2:17:47 AM - 			Version : [10.0]
3/9/2017 2:17:47 AM - 		Microsoft.VisualStudio.VST_All
3/9/2017 2:17:47 AM - 			Version : [12.0]
3/9/2017 2:17:47 AM - 		Microsoft.VisualStudio.VST_All
3/9/2017 2:17:47 AM - 			Version : [11.0]
3/9/2017 2:17:47 AM - 		Microsoft.VisualStudio.VST_All
3/9/2017 2:17:47 AM - 			Version : [10.0]
3/9/2017 2:17:47 AM - 
3/9/2017 2:17:47 AM - 	References         : 
3/9/2017 2:17:47 AM - Signature Details...
3/9/2017 2:17:47 AM - 	Extension is not signed.
3/9/2017 2:17:47 AM - 
3/9/2017 2:17:47 AM - Searching for applicable products...
3/9/2017 2:17:47 AM - Found installed product - Global Location
3/9/2017 2:17:47 AM - Found installed product - Visual Studio Community 2017
3/9/2017 2:17:47 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   ```
at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by DavidMoore** [comment]
Hi there! I actually have a new version coming soon that will support 2017; should be available in the next 2 weeks or less. Cheers, David

**Comment by morphx666** [comment]
Excellent news!
Thanks for letting me/us know.

**Comment by wasabii** [comment]
Has it been two weeks yet? :)
